#!/bin/bash

#
# SPDX-License-Identifier: GPL-3.0+ 
#
# Main compile gramado script
#
# (C) Copyright 2018
# Matheus Castello <matheus@castello.eng.br>
#

# check dependencies this works only in debian based distros
if [ $(dpkg-query -W -f='${Status}' nasm 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
	sudo apt-get install nasm
fi

if [ $(dpkg-query -W -f='${Status}' binutils 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
	sudo apt-get install binutils
fi

if [ $(dpkg-query -W -f='${Status}' gcc 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
	sudo apt-get install gcc
fi

if [ $(dpkg-query -W -f='${Status}' make 2>/dev/null | grep -c "ok installed") -eq 0 ];
then
	sudo apt-get install make
fi

# compile to target x86 since ARM files do not exist we have only x86 target
make x86
make link-x86
# move KERNEL.BIN to bin/
mv KERNEL.BIN bin/
# clean the output trash
make clean

# create virtual disk
make vhd-x86

# mount
sudo mkdir /mnt/gramado
sudo mount -o loop,offset=32256 GRAMADO.VHD /mnt/gramado/

##
# Copy content to disk
##

# bootloader
sudo cp bin/BM.BIN /mnt/gramado
sudo cp bin/BL.BIN /mnt/gramado

# kernel
sudo cp bin/KERNEL.BIN /mnt/gramado

# user space
sudo cp bin/INIT.BIN /mnt/gramado
sudo cp bin/SHELL.BIN /mnt/gramado
sudo cp bin/TASKMAN.BIN /mnt/gramado

# configs
sudo cp arch/x86/boot/vhd/INIT.TXT /mnt/gramado
sudo cp arch/x86/boot/vhd/USER.TXT /mnt/gramado

# bitmaps
sudo cp arch/x86/boot/vhd/images/BMP1.BMP /mnt/gramado
sudo cp arch/x86/boot/vhd/images/MOUSE.BMP /mnt/gramado
sudo cp arch/x86/boot/vhd/images/DENNIS.BMP /mnt/gramado
sudo cp arch/x86/boot/vhd/images/APP.BMP /mnt/gramado
sudo cp arch/x86/boot/vhd/images/FILE.BMP /mnt/gramado
sudo cp arch/x86/boot/vhd/images/FOLDER.BMP /mnt/gramado
sudo cp arch/x86/boot/vhd/images/TERMINAL.BMP /mnt/gramado
sudo cp arch/x86/boot/vhd/images/CURSOR.BMP /mnt/gramado

# fonts
sudo cp bin/NC2.FON /mnt/gramado

sudo cp bin/FCLASS.BIN /mnt/gramado
sudo cp bin/GRAMCC.BIN /mnt/gramado
sudo cp bin/JACKPOT.BIN /mnt/gramado	
sudo cp bin/TASCII.BIN /mnt/gramado
sudo cp bin/TEDITOR.BIN /mnt/gramado	
sudo cp bin/TGFE.BIN /mnt/gramado

# umount
sudo umount /mnt/gramado

echo "Success?"
