
all:
	make -C alpha/
	make -C base/
	make -C extra/
	make -C sdk/
	make -C tests/
clean:
	-rm -f *.o 
clean-all:
	-rm -f *.o 
#	-rm -f alpha/libs/
#	-rm -f alpha/toolkits/
	-rm -f base/bin/*.BIN
	-rm -f extra/bin/*.BIN
	-rm -f sdk/bin/*.BIN
	-rm -f tests/bin/*.BIN

