
    [-  
        This is a comment
        This file has 
        indexes for color
        paragraphs 
        break lines 
        and comments
    ]-

[s

#0
[c0]c
[c1]c
[c2]c
[c3]c

#1
[c0]c
[c1]c
[c2]c
[c3]c

[b 
    [p
    This is a paragraph 1    
    ]p

[b 
    [p
    This is a paragraph 2  
    ]p

#2
[c0]c
[c1]c
[c2]c
[c3]c

#3
[c0]c
[c1]c
[c2]c
[c3]c

    [- 
        comment End of file 
    ]-

[s   


