

#todo
all:
	make -C ./shell
	make -C ./cat
	make -C ./cmp
	make -C ./echo
	make -C ./false
	make -C ./reboot
	make -C ./true
	make -C ./sum
	make -C ./showfun
	make -C ./tprintf
	make -C ./uname
	
	
	make -C ./zfasm
	
	
	# gramc thing.    
#	make -C ./gramc
#	make -C ./gramcnf
	
	# c4 thing.
#	make -C ./c4  
#	make -C ./gramc4
	
#	make -C ./bazic   
	
# flags na compilaçao ... o assembly chama funcoes sem '_'
# e nos usaremos underline.
#	make -C ./fasm  
	
#	make -C ./unknown 
	make -C ./miniyacc 


# ...
	
	
	  
	
	
	
	
	


