

all:

	# launcher
	# The redpill makes the system initializes here.
	make -C launcher

	# launcher's itens
	make -C gdeshell
	make -C gramcode
	make -C sysmon
	# ...


	# compilers and interpreter
	#make -C c4
	#make -C gramc
	#make -C gramc4
	#make -C gramcnf
	
	# extra
	#make -C gfe
	#make -C reboot2
	#make -C reboot3
	
