

all:

	# main apps.
	make -C gdeshell
	make -C gramcode
	make -C sysmon
	# ...

	# launchers
	make -C launcher
	make -C leasy
	make -C lmedium
	make -C lhard

	# compilers and interpreter
	#make -C c4
	#make -C gramc
	#make -C gramc4
	#make -C gramcnf
	
	# extra
	#make -C gfe
	#make -C reboot2
	#make -C reboot3
	
