

;;USADAS EM FOPEN DE TEST
gramado_string_file1: db 'TEST.ASM', 0
;gramado_string_file2: db 'TEST.ASM', 0
gramado_string_fopen_code: db 'rw', 0

;; debug messages
gramado_string_step1: db 'Step1', 0Dh, 0Ah,0
gramado_string_step2: db 'Step2', 0Dh, 0Ah,0
gramado_string_step3: db 'Step3', 0Dh, 0Ah,0
gramado_string_step4: db 'Step4', 0Dh, 0Ah,0
gramado_string_step5: db 'Step5', 0Dh, 0Ah,0
gramado_string_step6: db 'Step6', 0Dh, 0Ah,0
gramado_string_step7: db 'Step7', 0Dh, 0Ah,0
gramado_string_step8: db 'Step8', 0Dh, 0Ah,0

