
all:

	make -C ./shutdown

	make -C ./reboot
	make -C ./vga1

	make -C ./shell
	make -C ./cat
	make -C ./tprintf
	make -C ./showfun
	make -C ./uname
	make -C ./cmp
	make -C ./sum
	make -C ./tascii
	make -C ./false
	make -C ./true

	make -C ./gramcnf
	
#make -C ./gramc4
