
all:

# Machine
	make -C shutdown
	make -C reboot
	make -C uname

# Test return
	make -C false
	make -C true

# Test file
	make -C cat

# Languages
	make -C gramcnf
	make -C c4
	make -C gramc4
	make -C miniyacc
	make -C showfun

# Shells
	make -C shell
	make -C sh7
	
# Outros
	make -C cmp
	make -C sum
	make -C vga1
	make -C tprintf
	make -C tascii
	make -C jackpot
	
