
# Compile extra commands.

all:

	make -C cmp/
#	make -C env/
#	make -C rect/
#	make -C replace/
	make -C showfun/
#	make -C socket1/
	make -C sum/
#	make -C tty/
#	make -C unknown/

	make -C udptest/

clean:
	-rm *.o
	-rm bin/*.BIN
clean-all:
	-rm *.o
	-rm bin/*.BIN
	
	

