#!/bin/sh
# Running Gramado OS on kvm.

	echo "~~~~>"

	qemu-system-x86_64 -hda GRAMADO.VHD \
	-m 256 \
	-smp 2 \
	-accel kvm \
	-serial stdio \
	-netdev type=user,id=net1 -device e1000,netdev=net1


