;
; File: lib16/s2menu16.inc:
;
; Descrição:
;     Menu inicial do Boot Manager. (16bit).
;     OBS: O menu de 16bit do Boot Manager está cancelado.
;
; 2015 - Created by Fred Nora.
;


;--------------------------------------
; MenuMain:
;     O usuário escolhe uma opção de inicialização.
;
MenuMain:  	
    ;    #Cancelado!
    RET

;
; Estruturas de dados para o menu do Boot Manager.
;

;Título.
menu_titulo1 db "16BIT Boot Manager ", BOOTMANAGER_VER, 0

;
; End.
;

