
# Compile SDK commands.

all:

	make -C c4/
	make -C gramc4/
	make -C gramcnf/
	make -C miniyacc/
	make -C n9/
	make -C n10/
	make -C n11/
	
clean:
	-rm *.o
	-rm bin/*.BIN
clean-all:
	-rm *.o
	-rm bin/*.BIN
	
	

