

all:

	# lib
	make -C libcore


	make -C c4

	make -C gdeshell
	make -C gfe

	make -C gramc 
	make -C gramc4 
	make -C gramcnf 

	make -C gramcode
	
	make -C launcher
	make -C noraterm
	make -C reboot2
	make -C sysmon
# ...

