
# This file builds all the components in gramado/ folder.

all:

# antigo primeiro cliente
	make -C init
# antigo window server
	make -C modr0

# client-side library
	#make -C libgws

# Gramado Core
# 'Final' game engine
# This is the end of the system initialization. No apps.
# The window server and the main client
	#make -C client
	#make -C server

# Gramado shell
# Extra stuff. Aps after system initialization.
	#make -C browser
	#make -C cmdline
	#make -C editor
	#make -C fileman
	#make -C logon    
	#make -C setup
	#make -C terminal  

