# Compiling some commands to run on Linux.

all:
	gcc ../cat/main.c     -o cat
	gcc ../c4/c4.c        -o c4
	gcc ../cmp/main.c     -o cmp
	gcc ../showfun/main.c -o showfun
	gcc ../unknown/main.c -o unknown
	gcc ../sum/main.c     -o sum
#	gcc ../jackpot/main.c -o jackpot

clean:
	-rm cat
	-rm c4
	-rm cmp
	-rm jackpot
	-rm showfun
	-rm unknown
	-rm sum  
	
