

#todo
all:
	make -C ./cat
	make -C ./cmp
	make -C ./echo
	make -C ./false
	make -C ./reboot
	make -C ./true
	make -C ./sum
	make -C ./showfun
	make -C ./tprintf
	make -C ./uname
	
	# gramc thing.    
	make -C ./gramc
	make -C ./gramcnf
	
	# c4 thing.
	make -C ./c4  
	make -C ./gramc4
	
	

# ...
	
	
	  
	
	
	
	
	


