
# Compile basic commands.

all:
	make -C cat/
#	make -C echo/
	make -C false/
	make -C reboot/
	make -C shutdown/
	make -C true/
	make -C uname/
	
clean:
	-rm *.o
	-rm bin/*.BIN
clean-all:
	-rm *.o
	-rm bin/*.BIN
	
	

